### ISSUE TITLE
Server Crash Issue

### ISSUE THREAD

**Issue by skohlhepp** [calclavia/Voltz-Mod-Pack#21]
Hello there, I have been having a problem with this for a few days now and I can't seem to figure out what causes it or what to do in response to it. If you could just push me in the right direction to fix this It would be greatly appreciated. I am not able to change versions of the modpack so that it not an option for me. If there is a fix please help me.

Here is the full error report:

http://pastebin.com/1B7F27r7

Please help me!

**Comment by Alex-hawks** [comment]
If you cannot update, then you cannot fix...

**Comment by skohlhepp** [comment]
Well what might I have to update? I mean I am on the latest version of voltz. And as far as i know, updating a specific mod will throw the whole modpack off right?

**Comment by calclavia** [comment]
Outdated
