### ISSUE TITLE
Updated to UE 1.2.0

### ISSUE THREAD

**Issue by calclavia** [calclavia/Voltz-Mod-Pack#4]

**Comment by cammygames** [comment]
The v7 was the last 1.1.3 so v8 is when i intend to update it

**Comment by calclavia** [comment]
MFFS Update for UE 1.2.0:
https://github.com/downloads/Thunderdark/ModularForceFieldSystem/ModularForceFieldSystemV2.2.8.1.17b.zip

**Comment by cammygames** [comment]
ok i just need @aidancbrady to fix mekanism
